- name: install asdf
  hosts: localhost
  vars_files:
    - data.yml
  tasks:
    - name: install binary
      include_tasks:
        file: ../../library/tasks/download_executable_binary.yml
    - name: set env vars
      lineinfile:
        path: $HOME/.config/env/vars.sh
        line: "{{ item }}"
        create: yes
        state: present
        insertafter: EOF
      loop:
        - export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
        - export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
        - export PATH="${ASDF_DATA_DIR}/shims:$PATH"
