- name: create directory
  become: true
  file:
    path: "{{ destination }}"
    state: directory
- name: run install script
  become: true
  shell: "{{ command }}"
- name: symlink
  file:
    src: "{{ path }}"
    dest: "$HOME/.local/bin/{{ name }}"
    state: link
