- name: uninstall libasound2t64
  hosts: localhost
  vars_files:
    - data.yml
  tasks:
    - name: uninstall apt package
      include_tasks:
        file: ../../library/tasks/uninstall_apt_package.yml
