# type: install script
name: # name of the executable file, as it will be invoked from the shell
script: # url of the install script  
destination: # destination directory for the script output, if custom install location is supported: `/opt/managed/version/{name}/{version}`
path: # full path of the executable, used for symlinking: `/opt/managed/version/{name}/{version}/{executable}`
