- name: uninstall zsh
  hosts: localhost
  vars_files:
    - data.yml
  tasks:
    - name: uninstall apt package
      include_tasks:
        file: ../../library/tasks/uninstall_apt_package.yml
    - name: delete .zshenv file
      file:
        path: "{{ destination }}"
        state: absent
