---
- name: Install packages from repository
  hosts: localhost
  vars_files:
    - data/packages.yaml
  tasks:
    - name: Include Task
      include_tasks:
        file: partials/install_packages.yml
      loop: "{{ items }}"
      # when: item.name == ''
  tags:
    - packages
- name: Install binaries from urls
  hosts: localhost
  vars_files:
    - data/binaries.yaml
  tasks:
    - name: Include Tasks 
      include_tasks:
        file: partials/install_binaries.yml
      loop: "{{ items }}"
      # when: item.name == ''
  tags:
    - binaries
- name: Install repos from git
  hosts: localhost
  vars_files:
    - data/repos.yaml
  tasks:
    - name: Include Task
      include_tasks:
        file: partials/install_repos.yml
      loop: "{{ items }}"
      # when: item.name == ''
  tags:
    - repos
