# type: executable binary
name: yt-dlp
url: https://github.com/yt-dlp/yt-dlp/releases/download/2026.03.17/yt-dlp_linux.zip
archive: yt-dlp_linux.zip
file: yt-dlp_linux
destination: /opt/managed/yt-dlp/2026.03.17
path: /opt/managed/yt-dlp/2026.03.17/yt-dlp_linux
